Repository shivamsouravjha/stock-frontend, pull requests merged in 2024-10, with the labels that each got.

#21 Updated the website title to StockSight and changed the logo to stag …
  index.html
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
  public/favicon.ico
  public/manifest.json
Labels: hacktoberfest

#31 Add: preview of xlsx sheet on website
  package.json
  src/hooks/useUpload.jsx
  src/pages/homepage.jsx
  yarn.lock
Labels: hacktoberfest, Hactoberfest-accepted

#35 Fixed an error, in the starting dev server command
  README.md
Labels: documentation, hacktoberfest, Hactoberfest-accepted, hacktoberfest2024

#51 feat: added contribution links of GitHub
  src/components/Footer.jsx
Labels: hacktoberfest, hacktoberfest2024, hacktoberfest-accepted

#53 Increase z-index of navbar
  src/components/Navbar.jsx
Labels: enhancement, hacktoberfest, hacktoberfest2024, hacktoberfest-accepted
